# --- Stage 1: Build Stage ---
FROM node:20-alpine AS builder

WORKDIR /app

COPY package*.json ./
COPY prisma ./prisma/

RUN npm ci

RUN npx prisma generate

COPY . .

RUN npm run build

RUN npm prune --production


FROM node:20-alpine

WORKDIR /app

# প্রথম স্টেজ থেকে শুধুমাত্র প্রয়োজনীয় ফাইলগুলো কপি করে আনা
COPY --from=builder /app/package*.json ./
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/generated ./generated
COPY --from=builder /app/prisma ./prisma

EXPOSE 5000

# অ্যাপ রান করার কমান্ড
CMD ["npm", "run", "start"]