version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rgpi_backend_api
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - DATABASE_URL=postgresql://root:secret@postgres_db:5432/rgpi_management?schema=public
    depends_on:
      - postgres_db

  postgres_db:
    image: postgres:15-alpine
    container_name: rgpi_postgres_db
    ports:
      - "5445:5432" # আপনার পিসির অন্য পোস্টগ্রেসের সাথে কনফ্লিক্ট এড়াতে লোকাল পোর্ট ৫৪৪৫ দিলাম
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=rgpi_management
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: